# Workflow name with better description
name: CI Pipeline Demonstration

# Trigger events
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

# Environment variables available to all jobs
env:
  ACCESS_ID: ${{ secrets.ACCESS_ID }}  # Changed from vars to secrets for sensitive data
  NODE_VERSION: 18  # Adding a sample version for demonstration

jobs:
  build-and-test:
    # Descriptive job name
    name: Build and Test Application
    # Runner environment
    runs-on: ubuntu-latest
    
    # Define job steps
    steps:
      # Checkout repository code
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      # Setup Node.js environment (example of a common tool)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      # Install dependencies (example step)
      - name: Install Dependencies
        run: npm ci
        
      # Echo the ACCESS_ID with masking
      - name: Display Access ID
        run: echo "Access ID is ${{ env.ACCESS_ID }}"
        
      # Example test step
      - name: Run Tests
        run: npm test || echo "No tests defined"
        
      # Example of conditional step
      - name: Debug Information
        if: failure()
        run: |
          echo "Previous step failed"
          env | sort
