name: CI Pipeline Demonstration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  ACCESS_ID: ${{ secrets.ACCESS_ID }}
  NODE_VERSION: 18

jobs:
  build-and-test:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}  # Removed cache: 'npm'
      - name: Install Dependencies
        run: npm install || echo "No package.json found, skipping install"
      - name: Display Access ID
        run: echo "Access ID is ${{ env.ACCESS_ID }}"
      - name: Run Tests
        run: npm test || echo "No tests defined"
      - name: Debug Information
        if: failure()
        run: |
          echo "Previous step failed"
          env | sort
